# STARTING MODE

STARTED_ON_RASPBERRY_PI = False  # True or False


MIN_PULSEWIDTH = 500
MED_MIN_PULSEWIDTH = 1000
MED_PULSEWIDTH = 1500
MED_MAX_PULSEWIDTH = 2000
MAX_PULSEWIDTH = 2500


# CHANGEABLE PARAMETERS

TRACKING_MODE = "hsv box"  # "hsv point", "hsv box", "backproject", "absdiff" or "opt flow"
SHOW_RECT = True  # True or False
SHOW_ROT_RECT = True  # True or False
TRACK_RECT_OR_ROT_RECT = "rect"  # "rect" or "rot rect"
SHOW_SIDE_WINS = False  # True or False
STARTING_PULSEWIDTH = MED_PULSEWIDTH  # MIN_PULSEWIDTH, MED_MIN_PULSEWIDTH, MED_PULSEWIDTH, MED_MAX_PULSEWIDTH or MAX_PULSEWIDTH
CAM_WIDTH = 640  # 320 or 640
CAM_HEIGHT = int(CAM_WIDTH * 0.75)  # 240 or 480


# FIXED PARAMETERS

CAM_SOURCE = 0
FLIP_HORIZONTALLY = 1
FRAME_COUNTER = 30
FPS_REAL_LIMIT = 30

MEDIAN_BLUR_SIZE = 5
BLUR_SIZE = 9
THRESHOLD_SENSITIVITY = 10
STEP_SIZE = 12
DELTA_H = 10
DELTA_S = 80
DELTA_V = 80

MIN_AREA = CAM_WIDTH * CAM_HEIGHT / 600
MIN_WIDTH_OR_HEIGHT = 20
if TRACKING_MODE in ("hsv point", "hsv box"):
	CONTOUR_AREA_FACTOR = 0.5
	MIN_LARGEST_AREA_EL_FACTOR = 0.13
	MAX_LARGEST_AREA_EL_FACTOR = 8
	MIN_LARGEST_AREA_AVG_FACTOR = 0.17
	MAX_LARGEST_AREA_AVG_FACTOR = 6
	BOUNDING_AREA_FACTOR = 0.6
elif TRACKING_MODE == "absdiff":
	CONTOUR_AREA_FACTOR = 0.25
	MIN_LARGEST_AREA_EL_FACTOR = 0.25
	MAX_LARGEST_AREA_EL_FACTOR = 4
	MIN_LARGEST_AREA_AVG_FACTOR = 0.33
	MAX_LARGEST_AREA_AVG_FACTOR = 3
	BOUNDING_AREA_FACTOR = 0.4
	
if STARTED_ON_RASPBERRY_PI:
	if CAM_WIDTH == 320:
		if TRACKING_MODE in ("hsv point", "hsv box", "backproject"):
			SERVO_COUNTER_LIMIT = 2
		elif TRACKING_MODE == "absdiff":
			SERVO_COUNTER_LIMIT = 14
		elif TRACKING_MODE == "opt flow":
			SERVO_COUNTER_LIMIT = 8
	elif CAM_WIDTH == 640:
		if TRACKING_MODE in ("hsv point", "hsv box", "backproject"):
			SERVO_COUNTER_LIMIT = 1
		elif TRACKING_MODE == "absdiff":
			SERVO_COUNTER_LIMIT = 7
		elif TRACKING_MODE == "opt flow":
			SERVO_COUNTER_LIMIT = 4
	LOW_LIST_LEN_LIMIT = 8
	HIGH_LIST_LEN_LIMIT = 20
	AREA_AND_CENTER_COUNTER_LIMIT = 4
else:
	SERVO_COUNTER_LIMIT = 0
	LOW_LIST_LEN_LIMIT = 10
	HIGH_LIST_LEN_LIMIT = 25
	AREA_AND_CENTER_COUNTER_LIMIT = 5

TEXT_SIZE = 0.6
CIRCLE_SIZE = 4
LINE_THICKNESS = 2
CV_WHITE = (255, 255, 255)
CV_BLACK = (0, 0, 0)
CV_BLUE = (255, 0, 0)
CV_CYAN = (255, 255, 0)
CV_GREEN = (0, 255, 0)
CV_YELLOW = (0, 255, 255)
CV_RED = (0, 0, 255)
CV_MAGENTA = (255, 0, 255)

SERVO_PIN = 17
FRAME_BORDER_BUFFER = CAM_WIDTH//8

if STARTED_ON_RASPBERRY_PI:
	if TRACKING_MODE in ("hsv point", "hsv box", "backproject"):
		LARGE_SPEED_FACTOR = 0.1  # 0, 0.06, 0.08, 0.1 or 0.12
	elif TRACKING_MODE in ("absdiff", "opt flow"):
		LARGE_SPEED_FACTOR = 0.14  # 0, 0.1, 0.12, 0.14 or 0.16
	SMALL_SPEED_FACTOR = LARGE_SPEED_FACTOR * 0.5
else:
	LARGE_SPEED_FACTOR = None
	SMALL_SPEED_FACTOR = None

MIN_FRAME_TIME = 1
KEY_ESC = 27